# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Query Data

on:
  push:
    branches: [ main ]

jobs:
  # data:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: "3.10"
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip poetry
  #       poetry install
  #   - name: Query
  #     run: |
  #       poetry run python azure.py

  #   - name: Upload a Build Artifact
  #     uses: actions/upload-artifact@v4.3.5
  #     with:
  #       name: data
  #       path: frontend/public/test_new.sqlite
              
  frontend:
    runs-on: ubuntu-latest
    # needs: [data]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-node@v2
      with:
        node-version: "20"

    - name: Install dependencies
      run: |
        npm ci
        npm build
      working-directory: frontend

    - name: Download Data
      uses: actions/download-artifact@v4.1.8
      with:  
        name: data
        path: frontend/dist/test_new.sqlite

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        # Path of the directory containing the static assets.
        path: frontend/dist
              
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v4.0.5              
